theme: jekyll-theme-cayman
title: Will Fleury
description: A Very Unmaintained Blog
markdown: kramdown

author: Will Fleury

google_analytics: UA-108117798-1

future: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
