theme: jekyll-theme-cayman
title: Will Fleury, PhD
description: Data Engineer, Data Architect, Machine Learning Practitioner
markdown: kramdown

author: Will Fleury

future: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
